import type { ThemeFile } from "./themeFile";

/**
 * TH-06: the themes that ship with Sketchor beyond plain Dark and Light.
 * They are ordinary TH-01 theme files — the same data an installed theme
 * plugin carries — laid over their `base`, so anything a built-in can do a
 * shared theme can do. Nord, Solarized and Monokai use those palettes' public
 * colour values (credited in NOTICE.md). `model3d` is left alone on purpose:
 * see the note in theme.ts.
 */

export const BUILTIN_THEMES: readonly ThemeFile[] = [
  {
    id: "high-contrast",
    name: "High Contrast",
    author: "Sketchor",
    base: "dark",
    tokens: {
      ui: {
        bg: "#000000",
        panel: "#0a0a0a",
        border: "#ffffff",
        text: "#ffffff",
        textDim: "#d0d0d0",
        accent: "#ffd400",
        accentSoft: "#4d4200",
        danger: "#ff6b6b",
      },
      canvas: {
        bg: "#000000",
        gridMinor: "#262626",
        gridMajor: "#4d4d4d",
        axis: "#8c8c8c",
        entity: "#ffffff",
        selected: "#ffd400",
        preview: "#00e5ff",
        snap: "#ff9500",
        handle: "#ffd400",
        measure: "#00ffd0",
        hover: "#00e5ff",
        measureLabelBg: "#003a33",
        reference: "#ff4040",
        connectivityHint: "#4da3ff",
        windowSelect: "#00b7ff",
        crossingSelect: "#00ff5a",
        closedRegionFill: "rgba(255, 255, 255, 0.22)",
        duplicateMarker: "#ffb347",
        crossingMarker: "#e08cff",
        origin: "#ffffff",
        originOff: "#8c8c8c",
        axisX: "#ff5555",
        axisY: "#55ff55",
      },
    },
  },
  {
    id: "classic-cad",
    name: "Classic CAD",
    author: "Sketchor",
    base: "dark",
    tokens: {
      ui: {
        bg: "#2b2b2b",
        panel: "#333333",
        border: "#4a4a4a",
        text: "#e6e6e6",
        textDim: "#a0a0a0",
        accent: "#1e90ff",
        accentSoft: "#1d3b5c",
      },
      canvas: {
        bg: "#000000",
        gridMinor: "#1a1a1a",
        gridMajor: "#2e2e2e",
        axis: "#555555",
        entity: "#ffffff",
        selected: "#00ffff",
        preview: "#ffff00",
        snap: "#ffff00",
        handle: "#3a6bff",
        measure: "#00ff00",
        hover: "#ff7fff",
        measureLabelBg: "#003300",
        reference: "#ff0000",
        windowSelect: "#3a8bff",
        crossingSelect: "#00ff00",
        closedRegionFill: "rgba(255, 255, 255, 0.14)",
        axisX: "#ff0000",
        axisY: "#00ff00",
      },
    },
  },
  {
    id: "blueprint",
    name: "Blueprint",
    author: "Sketchor",
    base: "dark",
    tokens: {
      ui: {
        bg: "#0f2f63",
        panel: "#12396f",
        border: "#2a5aa3",
        text: "#eaf2ff",
        textDim: "#9db9e6",
        accent: "#6cb2ff",
        accentSoft: "#1f4a8c",
        danger: "#ff8a8a",
      },
      canvas: {
        bg: "#123c7c",
        gridMinor: "rgba(255, 255, 255, 0.10)",
        gridMajor: "rgba(255, 255, 255, 0.22)",
        axis: "rgba(255, 255, 255, 0.40)",
        entity: "#ffffff",
        selected: "#ffe36e",
        preview: "#ffe36e",
        snap: "#ffd23f",
        handle: "#ffe36e",
        measure: "#9be7ff",
        hover: "#9be7ff",
        measureLabelBg: "#0a2a5c",
        reference: "#ff8a8a",
        connectivityHint: "#8fb8ff",
        windowSelect: "#9be7ff",
        crossingSelect: "#a6ffb0",
        closedRegionFill: "rgba(255, 255, 255, 0.14)",
        duplicateMarker: "#ffd23f",
        crossingMarker: "#e0b3ff",
        origin: "#cfe3ff",
        originOff: "#6f94d1",
        axisX: "#ff9a9a",
        axisY: "#a6ffb0",
      },
    },
  },
  {
    id: "paper",
    name: "Paper",
    author: "Sketchor",
    base: "light",
    tokens: {
      ui: {
        bg: "#f5f2ec",
        panel: "#fffdf8",
        border: "#d9d2c3",
        text: "#1d1b17",
        textDim: "#6f685a",
        accent: "#1a56db",
        accentSoft: "#dbe4fb",
      },
      canvas: {
        bg: "#ffffff",
        gridMinor: "#ececec",
        gridMajor: "#d6d6d6",
        axis: "#b0b0b0",
        entity: "#000000",
        selected: "#1a56db",
        preview: "#1a56db",
        handle: "#1a56db",
        windowSelect: "#1a56db",
        origin: "#000000",
      },
    },
  },
  {
    id: "nord",
    name: "Nord",
    author: "Sketchor (Nord palette)",
    base: "dark",
    tokens: {
      ui: {
        bg: "#2e3440",
        panel: "#3b4252",
        border: "#4c566a",
        text: "#eceff4",
        textDim: "#a3adc0",
        accent: "#5e81ac",
        accentSoft: "#3b4f6b",
        danger: "#bf616a",
      },
      canvas: {
        bg: "#272c36",
        gridMinor: "#2e3440",
        gridMajor: "#3b4252",
        axis: "#4c566a",
        entity: "#eceff4",
        selected: "#88c0d0",
        preview: "#88c0d0",
        snap: "#ebcb8b",
        handle: "#88c0d0",
        measure: "#8fbcbb",
        hover: "#81a1c1",
        measureLabelBg: "#2a3d3d",
        reference: "#bf616a",
        connectivityHint: "#5e81ac",
        windowSelect: "#81a1c1",
        crossingSelect: "#a3be8c",
        duplicateMarker: "#d08770",
        crossingMarker: "#b48ead",
        origin: "#d8dee9",
        originOff: "#4c566a",
        axisX: "#bf616a",
        axisY: "#a3be8c",
      },
      code: { keyword: "#81a1c1", number: "#b48ead", comment: "#616e88", error: "#bf616a" },
    },
  },
  {
    id: "solarized-dark",
    name: "Solarized Dark",
    author: "Sketchor (Solarized palette)",
    base: "dark",
    tokens: {
      ui: {
        bg: "#002b36",
        panel: "#073642",
        border: "#124553",
        text: "#93a1a1",
        textDim: "#839496",
        accent: "#268bd2",
        accentSoft: "#0b4a63",
        danger: "#dc322f",
      },
      canvas: {
        bg: "#00252f",
        gridMinor: "#04323d",
        gridMajor: "#0a4150",
        axis: "#586e75",
        entity: "#eee8d5",
        selected: "#268bd2",
        preview: "#2aa198",
        snap: "#b58900",
        handle: "#268bd2",
        measure: "#2aa198",
        hover: "#6c71c4",
        measureLabelBg: "#0a4a46",
        reference: "#dc322f",
        connectivityHint: "#268bd2",
        windowSelect: "#268bd2",
        crossingSelect: "#859900",
        duplicateMarker: "#cb4b16",
        crossingMarker: "#d33682",
        origin: "#93a1a1",
        originOff: "#586e75",
        axisX: "#dc322f",
        axisY: "#859900",
      },
      code: { keyword: "#268bd2", number: "#d33682", comment: "#586e75", error: "#dc322f" },
    },
  },
  {
    id: "solarized-light",
    name: "Solarized Light",
    author: "Sketchor (Solarized palette)",
    base: "light",
    tokens: {
      ui: {
        bg: "#fdf6e3",
        panel: "#eee8d5",
        border: "#d6cfb8",
        text: "#073642",
        textDim: "#586e75",
        accent: "#268bd2",
        accentSoft: "#d3e3ea",
        danger: "#dc322f",
      },
      canvas: {
        bg: "#fdf6e3",
        gridMinor: "#f1ead6",
        gridMajor: "#e3dbc2",
        axis: "#b8b49f",
        entity: "#073642",
        selected: "#268bd2",
        preview: "#2aa198",
        snap: "#cb4b16",
        handle: "#268bd2",
        measure: "#2aa198",
        hover: "#6c71c4",
        measureLabelBg: "#e0efe8",
        reference: "#dc322f",
        connectivityHint: "#268bd2",
        windowSelect: "#268bd2",
        crossingSelect: "#859900",
        duplicateMarker: "#b58900",
        crossingMarker: "#d33682",
        origin: "#586e75",
        originOff: "#b8b49f",
        axisX: "#dc322f",
        axisY: "#859900",
      },
      code: { keyword: "#268bd2", number: "#d33682", comment: "#93a1a1", error: "#dc322f" },
    },
  },
  {
    id: "monokai",
    name: "Monokai",
    author: "Sketchor (Monokai palette)",
    base: "dark",
    tokens: {
      ui: {
        bg: "#272822",
        panel: "#1e1f1c",
        border: "#3e3d32",
        text: "#f8f8f2",
        textDim: "#a59f85",
        accent: "#f92672",
        accentSoft: "#5a1d37",
        danger: "#f92672",
      },
      canvas: {
        bg: "#1e1f1c",
        gridMinor: "#272822",
        gridMajor: "#33342b",
        axis: "#4a4a3d",
        entity: "#f8f8f2",
        selected: "#66d9ef",
        preview: "#a6e22e",
        snap: "#e6db74",
        handle: "#66d9ef",
        measure: "#a6e22e",
        hover: "#fd971f",
        measureLabelBg: "#2b3a14",
        reference: "#f92672",
        connectivityHint: "#3f8fa0",
        windowSelect: "#66d9ef",
        crossingSelect: "#a6e22e",
        duplicateMarker: "#fd971f",
        crossingMarker: "#ae81ff",
        origin: "#f8f8f2",
        originOff: "#75715e",
        axisX: "#f92672",
        axisY: "#a6e22e",
      },
      code: { keyword: "#f92672", number: "#ae81ff", comment: "#75715e", error: "#f92672" },
    },
  },
];

export function builtinTheme(id: string): ThemeFile | undefined {
  return BUILTIN_THEMES.find((t) => t.id === id);
}
